### ISSUE TITLE
more (missing) resolutions and Format support for AVPlayer in v1.4

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#276] opened 2022-08-22 05:18 UTC
**Currently, AVPlayer in v1.4 (as of build 82) supports only 3 resolutions and 1 format: `720p (stream), 360p (stream), 144p (stream)`**.

and there are **missing resolutions like `240p, 480p, 1080p` and also the format like `HLS`**.

I hope this is fixed.

_ps. I'm reporting more of AVPlayer recently because I find this convenient from time to time. hope AVPlayer looks as normal as possible._

**Comment by arekf** [comment] 2022-08-23 15:55
Fixed in build 85

**Closed by arekf** 2022-08-23 15:55 UTC

**Comment by aniqueta** [comment] 2022-12-06 07:50
@arekf In build 112, I only see three resolutions as noted above. I wanted to use AVPlayer for features like AirPlay and to watch at 1080p or ideally 4K. I couldn't find any other issues related to this, so posting here. I suspect AVPlayer is behaving as intended, given the focus on MPV? Thanks.

**Comment by arekf** [comment] 2022-12-06 08:34
HLS is adaptive format and quality is selected by the system depending on network conditions, you can't create quality profile to force specific resolution with HLS. This is noted in the app when adding/editing quality profile.

**Comment by piejanssens** [comment] 2023-12-04 10:46
@arekf If I understand it correctly, AVPlayer is likely the best option for most users (integration, scrubbing, skip 10s, PIP, ..)
Atm the default profile HLS 720p makes people think this is locked at 720p and makes them switch to MPV while HLS.
Perhaps the UI could disable the resolution section and put 'best' in the text of the profile when HLS is selected?
