### ISSUE TITLE
Can't manage to close dialog window

### ISSUE THREAD

**Issue by JD342** [yattee/yattee#257] opened 2022-08-10 13:24 UTC
Hi, this is the first day I use this application, and it seems that I found a bug here.

When I clicked a button to add a video on the playlist, it would display a notification titled "You have no Playlists", asking to "Open "Playlists" tab to create a new one". I can't seem to be able to dismiss this notification. If I click outside of the box, it won't disappear. There is no "x" button, and pressing any key in the keyboard does nothing. This also prevents Yattee from being closed. I had to force quit through the Activity Monitor.

![image](https://user-images.githubusercontent.com/11964463/183912431-172f5d63-7e80-4c58-9c6a-a5c758731d95.png)

**Comment by arekf** [comment] 2022-08-15 12:49
Duplicate of #246

**Closed by arekf** 2022-08-15 12:49 UTC
