### ISSUE TITLE
size responsive mpv controls on full screen mode 

### ISSUE THREAD

**Issue by debpalash** [yattee/yattee#267] opened 2022-08-19 11:29 UTC
control area and buttons could be little bigger in both rotation modes.

![777A5863-F650-499A-9DD4-3804D484BDCC](https://user-images.githubusercontent.com/4178343/185608287-f2ef5f35-21ce-42a6-850f-206bfa464979.png)

**Comment by arekf** [comment] 2022-08-19 11:41
Duplicate of #195

**Closed by arekf** 2022-08-19 11:41 UTC
