### ISSUE TITLE
View subscription list on iOS and AppleTV

### ISSUE THREAD

**Issue by paulmorabito** [yattee/yattee#337] opened 2022-11-04 17:29 UTC
Hi,

Is there a way to view my list of subscriptions on the iOS and AppleTV apps? (Rather than just the most recent videos from them). On iPadOS, I can do this but can't figure how on the others.

Many thanks for a wonderful app!

**Comment by arekf** [comment] 2022-11-13 12:44
This is planned. Closing as duplicate of #141

**Closed by arekf** 2022-11-13 12:44 UTC
