### ISSUE TITLE
[Feature request]  open channel  by clicking channel logo

### ISSUE THREAD

**Issue by F3000** [yattee/yattee#294] opened 2022-09-05 23:32 UTC
I have forwarded a video via safari extension into Yattee .

But here there is a missing way to  open channel where the video is from . 

Workaround :
Close the video and search manually after channel 

![image](https://user-images.githubusercontent.com/8161283/188520607-5f35426e-40a2-4811-8a48-cbac1489e5e3.jpeg)

**Comment by arekf** [comment] 2022-09-06 07:42
Tap and hold this channel logo, you will open menu where you can open channel and more

**Comment by arekf** [comment] 2022-09-06 07:42
Duplicate of #250

**Closed** 2022-09-06 07:43 UTC
