### ISSUE TITLE
Typing in search bar is slow 

### ISSUE THREAD

**Issue by UnixPhonez** [yattee/yattee#209] opened 2022-07-02 18:24 UTC
When typing in the Yattee search bar for videos it’s slow seems super slow 

device:
iPhone X 
15.5

**Comment by arekf** [comment] 2022-09-13 20:57
Search performance has been improved throughout recent builds, I think it's ok to close this now

**Comment by LennyPenny** [comment] 2022-09-13 20:59
I disagree, as soon auto suggestions pop it goes slow again - I guess they are blocking somehow

**Comment by arekf** [comment] 2022-09-13 21:07
> I disagree, as soon as suggestions pop it goes slow again - I guess they are blocking the text input somehow

I cannot reproduce that. Please add device, system version and possibly screen recording because I don't understand where's the issue now.

**Comment by LennyPenny** [comment] 2022-09-14 14:27
iphone X ios 15

- https://user-images.githubusercontent.com/4027243/190182139-f1096c2e-a629-427e-a9eb-a46575b34bef.MOV

typing speed was about constant but after the "very" there started to be a ~1s delay

**Comment by arekf** [comment] 2022-12-06 12:52
@LennyPenny @UnixPhonez could you check if 1.4.2 got it fixed for you too?

**Comment by lenny-optiopay** [comment] 2022-12-06 12:55
yes its working perfectly now!

**Comment by LennyPenny** [comment] 2022-12-06 12:57
Yes it's working perfectly now!

**Comment by arekf** [comment] 2022-12-06 13:20
Great, closing it for now then.

**Closed by arekf** 2022-12-06 13:20 UTC
Labels: bug
