### ISSUE TITLE
Invidious subscriptions not showing feed

### ISSUE THREAD

**Issue by sallyFoster** [yattee/yattee#549] opened 2023-10-24 01:15 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Invidious subscriptions are not showing any feed

### Expected Behavior

Invidious subscribed instances should show content in the feed the same way that the piped instances do.

### Device & OS Version

iOS 17.0.1

### App Build

v.1.5

### Screenshots, Videos and other files

![IMG_9235](https://github.com/yattee/yattee/assets/104597302/d711fb35-9075-4e6d-8d1f-fd0cd4192e41)

**Comment by arekf** [comment] 2023-11-03 18:23
You need to provide details on the instance where this can be reproduced.

**Comment by stonerl** [comment] 2024-05-03 08:06
@sallyFoster as @arekf said, this seems to be a problem with the instance. Does this still happen? I cannot reproduce this with my local instances.

**Comment by sallyFoster** [comment] 2024-05-05 20:03
@stonerl Yes, it is still happens. This is the instance that it happens in: vid.puffyan.us

**Comment by stonerl** [comment] 2024-05-20 18:45
@sallyFoster I'm closing this one. I cannot reproduce this on my instance and I also cannot register an account at vid.puffyan.us IMHO the instance is broken. Try to us another one.

**Closed by stonerl** 2024-05-20 18:45 UTC
Labels: bug, question, Invidious
