### ISSUE TITLE
Thumbnails don't load if the instance is behind HTTP basic login

### ISSUE THREAD

**Issue by TheFrenchGhosty** [yattee/yattee#731] opened 2024-08-09 02:01 UTC
Context: I have been hosting a semi-private Invidious since years now https://pussthecat.org/invidious/ it now has dozens of users. I recently got an iPad Pro, and Yattee was one of the first app I installed, and I got this problem.

If the Invidious instance used is behind a basic http login ( https://username:password@domain.ext - this is the direct login URL and it's what's setup in Yattee) , thumbnails will be broken, everything else seems to be working.

Users avatar will load fine

Videos play perfectly otherwise, and comments are displayed perfectly. (A side problem: Enabling Proxy Video will make it break.)

This just makes it more "rough" and far less confortable to use Yattee, but it's still usable.

Maybe related #725

Note: 

- I can provide you an access to my instance for testing.

- FreeTube has the same issue https://github.com/FreeTubeApp/FreeTube/issues/686

**Comment by AndrzejStecyk** [comment] 2024-08-21 11:16
This is an issue with your invidious instance.
If you're using docker-compose you need to uncomment and fill these 3 parameters:
        domain: <your_domain>
        external_port: <docker_container_port>
        https_only: <True/false> 

In my case, I do not have a domain configured so I'm using my local IP address of a server that hosts docker containers.
Port is in my case a default one - 3000 and I don't use SSL so https_only is false for me
My section INVIDIOUS_CONFIG looks like this:
`      INVIDIOUS_CONFIG: |
        db:
          dbname: <redacted>
          user: <redacted>
          password: <redacted>
          host: invidious-db
          port: 5432
        check_tables: true
        domain: 241.138.233.124
        external_port: 3000
        https_only: false 
        # statistics_enabled: false
        hmac_key: <redacted>`

If you do not use docker, you must find a config file and change those parameters.
This should solve your issue.

**Comment by retrocaster** [comment] 2024-08-27 22:22
Thanks @AndrzejStecyk , I think your suggestion was what fixed the missing images in my case.

**Comment by TheFrenchGhosty** [comment] 2024-08-27 23:01
@AndrzejStecyk that's absolutely not related.

My instance is correctly configured.

**Comment by stonerl** [comment] 2024-08-28 09:57
Closing this one in favor of #356

**Comment by TheFrenchGhosty** [comment] 2024-08-28 10:09
@stonerl that's a completely different issue.

**Comment by stonerl** [comment] 2024-08-28 10:11
What do you mean by basic HTTP login then? You don't use HTTPS but rather HTTPS to access invidious?

Like `http://myinvidious.local` or `http://192.168.0.5`

**Comment by stonerl** [comment] 2024-08-28 10:21
I took a look at your description again. It is the same issue. We need to implement HTTP Headers for this to work.

**Closed** 2024-08-31 10:46 UTC
Labels: enhancement, Piped, Invidious

**Comment by TheFrenchGhosty** [comment] 2024-08-31 16:13
Testflight build tested:

- Video thumbnails properly load now
- Still a (minor) issue where channel avatar don't load (if the actual channel page wasn't accessed first)
<img width="1024" alt="yatteetest" src="https://github.com/user-attachments/assets/8c134450-9ce1-427d-8a4d-eb14db7ee0cc">

**Comment by arekf** [comment] 2024-08-31 16:32
> Still a (minor) issue where channel avatar don't load (if the actual channel page wasn't accessed first) - this acts the same way on the release build

It's not a bug, channel thumbnails are not returned by Invidious API for related videos so it's displayed only if it was cached first by visiting the channel

**Comment by stonerl** [comment] 2024-09-01 09:59
@TheFrenchGhosty could you open a separate issue for this. Just so we don't forget it.

**Comment by andrynhk** [comment] 2025-10-29 19:46
can confirm it's still an issue, my instance is configured correctly

domain: inv.domain.com
external_port: 443
https_only: true

**Comment by psarchives** [comment] 2026-01-05 05:44
@AndrzejStecyk That fixed it for me thank you. I thought 127.0.0.1 would work but didn't resolve it. Once I added my local ip it instantly loaded thumbnails after asking for local network access. Alternatively if you're using a vpn like tailscale etc, the node ip hosting your invidious docker container will also work.
