### ISSUE TITLE
Can't play any videos off my private Piped server

### ISSUE THREAD

**Issue by brodo** [yattee/yattee#404] opened 2023-02-23 09:59 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I've set up a private a Piped server (fresh install) which works without problems when I use the web UI.
I've installed Yattee and it works for me with with public servers but does not play video when I use my server.

When I set the player to MVP I get  "Opening 1080p Stream - 0%" which stays ant 0%. When I set the player to AVPlayer I get a popup saying "Failed loading video - resource unavailable".

Is there any way to debug this on yattees end? Is there a way to find out which resource exactly is unavailable?

I've tested this on iOS and macOS with the same results.

### Expected Behavior

The videos should start playing.

### Device & OS Version

macOS 13.2.1, iOS 16.3.1 

### App Build

1.4.2 build 112 on both Mac and iPhone

### App Settings

I've provided a custom location.

**Comment by arekf** [comment] 2023-02-25 14:09
This issue has been reported a few times and seems to be happening only on some instances but it's hard to say what's causing it. I don't have such issues with my private Piped instance. It may be some configuration difference that we've been unable to understand so if anyone has any clue, I'd like to hear it.

Closing as duplicate of #400

**Closed by arekf** 2023-02-25 14:09 UTC
Labels: bug

**Comment by wweevv-johndpope** [comment] 2023-03-21 03:07
Hi - cool app - I was looking freetube app - which plays youtube videos - then that lead me to piped - and this native ios app. But it doesn't actually play youtube videos? I get that error Failed Loading Video when i paste a link from youtube.
