### ISSUE TITLE
No audio with MPV player

### ISSUE THREAD

**Issue by m-ruhl** [yattee/yattee#545] opened 2023-10-16 15:40 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

When selecting the MPV player over the AV player.. there is no audio.

### Expected Behavior

It should play audio with the MPV player

### Device & OS Version

iPad,iPhone & tvOS 17.0.x

### App Build

Tested on 155 and 166

**Comment by stonerl** [comment] 2024-05-03 08:02
Is this still an issue? Cannot reproduce this with the latest build (181)

**Comment by stonerl** [comment] 2024-05-18 09:23
Closing this one since the issue doesn't seem to exist any.

**Closed** 2024-05-18 09:23 UTC
Labels: bug, question
