### ISSUE TITLE
Disabling Playback Mode does not clear settings

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#477] opened 2023-05-27 04:01 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

If you enable Controls: Playback Mode and change to loop and then proceed to disable Playback Mode the videos will still loop. 

This also causes other bugs like stuck "loading streams..." message etc.

### Expected Behavior

The loop settings should reset when Playback Mode is disabled.

### Device & OS Version

tvOS 16.5

### App Build

151

**Comment by stonerl** [comment] 2024-05-03 14:52
@bbsixzz This should be fixed by now. Cannot reproduce this with the latest build (181)

**Closed** 2024-05-03 22:59 UTC
Labels: bug, question
