### ISSUE TITLE
Reloading subscriptions every other time pushes videos down

### ISSUE THREAD

**Issue by ooosssay** [yattee/yattee#556] opened 2023-11-11 16:38 UTC
### Guidelines

- [x] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I would open my subscriptions in Yattee then when I try to reload my subscriptions it pushes the videos down. This only happens every other time I refresh.

### Expected Behavior

To refresh with the videos staying in place.

### Device & OS Version

iPad, iOS 16.2

### App Build

169

### Screenshots, Videos and other files

https://github.com/yattee/yattee/assets/129241633/95ffaa6e-a940-4204-af6a-3b5552006006

**Comment by stonerl** [comment] 2024-05-20 18:40
@ooosssay is this still happening with 183?

**Comment by ooosssay** [comment] 2024-05-20 18:49
Yes (184)

https://github.com/yattee/yattee/assets/129241633/44b5e128-ea9d-479b-a1c7-518cc572d399

**Comment by stonerl** [comment] 2024-05-26 11:54
Which Piped instance are you using?

**Comment by ooosssay** [comment] 2024-05-26 22:32
I am using https://piped.nosebs.ru/

**Comment by stonerl** [comment] 2024-08-20 17:44
Closing this one since it is a duplicate of #458

**Closed** 2024-08-20 17:44 UTC
Labels: bug
