### ISSUE TITLE
Progress bars in cells flash when moving up/down

### ISSUE THREAD

**Issue by retrocaster** [yattee/yattee#705] opened 2024-06-20 19:40 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

While scrolling up or down in a list of "Cells", there is a very noticeable flashing that occurs in the area of any progress bars (ie. content cells that have previously been started).  The thumbnail images in the cells are already fully loaded and the flashing even persists after the scroll animation is done: You move down a row, the animation to reposition the new row completes, but then you see any visible progress bars flashing for about 1 second

### Expected Behavior

Progress bars should not have a strange flashing

### Device & OS Version

tvOS 17.5.1 [21L580]

### App Build

1.5.1 (build 174)

**Comment by retrocaster** [comment] 2024-08-28 17:07
I'm now on version 1.5.2 (build 190) and can confirm that this issue still occurs

**Comment by stonerl** [comment] 2024-08-29 18:42
This is a duplicate of #485.

**Closed by stonerl** 2024-08-29 18:42 UTC
Labels: bug, duplicate, tvOS
