### ISSUE TITLE
Can You Add A Download Feature 

### ISSUE THREAD

**Issue by Sloom128** [yattee/yattee#550] opened 2023-10-28 17:09 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

New feature

### Describe the feature

Download Button And Add A New Section For Downloads

**Comment by arekf** [comment] 2023-11-03 18:21
Not planned at the moment.

Duplicate of #17

**Closed by arekf** 2023-11-03 18:21 UTC
Labels: enhancement
