### ISSUE TITLE
#Shorts thumbnail sizing issue

### ISSUE THREAD

**Issue by UnixPhonez** [yattee/yattee#244] opened 2022-07-20 21:38 UTC
Video's made with #shorts are having an sizing issue, as the thumbnail being displayed is compress down due to the video originally being recorded in portrait and not landscape. My guess would shorts are going to be needed to be supported as playing short videos causes the description to be cut out / inaccessible

**Comment by arekf** [comment] 2022-07-20 21:46
Duplicate of #218

**Closed by arekf** 2022-07-20 21:46 UTC
