### ISSUE TITLE
add option `Number of videos shown in feed` for subscriptions

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#225] opened 2022-07-07 09:28 UTC
There is a option for Invidious Instance: Number of videos shown in feed for subscriptions and I think it will be a good one to have in the settings.

**Comment by suymur** [comment] 2023-01-01 17:46
Duplicate of #301 
> EDIT: If you go to your account settings in Invidious there is an option called "Number of videos to show in feed" I set this to 1000 and the issue is resolved.

This solved it for me...!

**Comment by stonerl** [comment] 2024-05-18 09:33
@bachig26  There is an option in Yattee's Advanced section called Maximum feed items. I guess this is what you where asking for.

**Closed** 2024-05-18 09:33 UTC
