### ISSUE TITLE
[Issue/Bug] Channel not showing full video library 

### ISSUE THREAD

**Issue by GAMZPRISM2** [yattee/yattee#256] opened 2022-08-06 04:52 UTC
YouTube Channel only showing videos back to 7 Months ago, however on piped the channel goes years back, additionally these videos from years ago appear in search but not under the channel, here is the channel link: https://piped.kavin.rocks/channel/UCB2S3fP0llkRrTxgth5InNw

Have even changed piped servers same result.

**Comment by arekf** [comment] 2022-08-06 10:16
Duplicate of #135

**Closed** 2022-08-06 10:17 UTC
