### ISSUE TITLE
fix needed: settings button

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#226] opened 2022-07-07 09:30 UTC
it's about the settings button _(general settings button at left, not player setting button)_, it sometimes doesn't work properly like I can see the clicking animation on the settings button but doesn't open the settings.
I need to restart the app to make work, this doesn't happen all the time but happens every week few times.

#### Screenshot
![image](https://user-images.githubusercontent.com/96393348/187436464-482ea451-4803-4e29-b109-990fb1a04782.jpeg)

**Comment by Permanently** [comment] 2022-08-30 12:20
Been having this issue recently; it's not just you.

**Comment by arekf** [comment] 2022-08-31 20:27
Finally found a way to reproduce: press locations/accounts menu (globe icon) then without closing the context menu tap on settings icon. It will block opening settings sheet until app is restarted.

I've created a minimal project and I can reproduce. It's definitely a bug in SwiftUI. As far as I can see it was not resolved in iOS 16. I will send the test project and report to Apple. Hopefully it can be fixed by them someday...

**Comment by stonerl** [comment] 2024-08-28 09:59
Seems to be fixed? Closing this one.

**Closed by stonerl** 2024-08-28 09:59 UTC
Labels: SwiftUI bug
