### ISSUE TITLE
[Bug] [iOS] Unable to open Settings

### ISSUE THREAD

**Issue by bachig26** [yattee/yattee#70] opened 2022-03-20 14:21 UTC
I experienced the issue with **settings not being open after the editing to adding a new Invidious or Piped instances**. 

After selecting an instance account on the homepage and while I was trying to change some setting options, the settings icon doesn't function as it should intend to be.

**To work, I need to restart or close and open the yattee app to change the desired settings and use the app. also, the app slows down after this crash and feels like it consumes more processing power or ram at this point.**

yattee version: v1.3.2
iOS version: 15.4

**Comment by arekf** [comment] 2022-12-04 00:16
Closing as duplicate of #226

**Closed by arekf** 2022-12-04 00:16 UTC
Labels: bug, unreproducible
