### ISSUE TITLE
[macOS/iPadOS/iOS] No thumbnails in 'Trending' or in a 'Channel' page for kavin.rocks while they are showing on the website

### ISSUE THREAD

**Issue by piejanssens** [yattee/yattee#574] opened 2023-12-04 08:05 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Only on the "Trending" section in the Yattee apps, I have no thumbnails.

Is there an API path that I can test https://pipedapi.kavin.rocks with to see if the issue is on the server side or not?

<img width="920" alt="image" src="https://github.com/yattee/yattee/assets/829098/a107ad5e-197a-49d2-9332-c85d5699b40a">

### Expected Behavior

Show the same thumbnails as they are shown on the website directly:

<img width="1430" alt="image" src="https://github.com/yattee/yattee/assets/829098/187fe1bf-ebc3-4e45-8953-c2b8da4bef9b">

### Device & OS Version

macOS 14.1.1

### App Build

1.5 (166)

**Comment by eightsheep67** [comment] 2023-12-08 06:43
same problem here

**Comment by jampoyman** [comment] 2023-12-22 09:32
Encountering this as well. Thought it was because of the invidious instance I was using so I setup my own and the issue still persists.

**Comment by skynet2982** [comment] 2024-01-02 14:54
@jampoyman can you explain what did you do ?

**Comment by jampoyman** [comment] 2024-01-02 15:25
> @jampoyman can you explain what did you do ?

i had to change some lines in the config.yml file, already forgot what though, sorry

**Comment by rickykresslein** [comment] 2024-01-03 10:28
Any chance you could look back at what you did? That would be really helpful to have posted here for those of us who are still having this issue.

**Comment by j-martin** [comment] 2024-04-27 19:38
Confirming https://github.com/yattee/yattee/issues/574#issuecomment-1878354840 fixed my issue.

**Comment by stonerl** [comment] 2024-05-03 08:01
Closing this one, since it is not a Yattee issue but rather an issue with the instance. Couldn't reproduce this on my personal piped instance. Please don't hesitate to open it again, if it happens once more with the latest build (181 ATM).

**Closed by stonerl** 2024-05-03 08:01 UTC
Labels: bug, unreproducible, Piped
