### ISSUE TITLE
Add Subscription feed to Top Shelf area in Apple TV

### ISSUE THREAD

**Issue by retrocaster** [yattee/yattee#823] opened 2024-09-20 00:07 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

New feature

### Describe the feature

It would be great if Yattee could make use of the Apple TV's Top Shelf by displaying the most recent items from the Subscription feed when the Yattee app is highlighted as part of the top row of apps. It's a convenient way to be able to launch directly into content without having to navigate into the app first. The Infuse app, Netflix, and Prime Video are examples of apps that make use of Top Shelf.

Info about Apple TV's "Top Shelf" : https://developer.apple.com/design/human-interface-guidelines/top-shelf

**Comment by arekf** [comment] 2024-09-20 06:06
Duplicate of #9

**Closed by arekf** 2024-09-20 06:06 UTC
Labels: enhancement
