### ISSUE TITLE
iOS: Exit full screen video when finished

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#663] opened 2024-05-09 23:32 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found feature request like this

### Type

Usability improvement

### Describe the feature

When video finishes with close video and player on end set to off the screen remains black and you have to manually exit the full screen mode.

I would like the behavior to automatically exit full screen mode so I can read comments etc.

**Comment by stonerl** [comment] 2024-08-28 09:18
Duplicate of #105

**Closed** 2024-08-28 09:19 UTC
Labels: enhancement
