### ISSUE TITLE
tvOS AVPlayer back to MPV loses progress

### ISSUE THREAD

**Issue by bbsixzz** [yattee/yattee#445] opened 2023-05-10 00:41 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Going from MPV to AVPlayer in a video keeps progress. Going back loses progress.

### Expected Behavior

Ability to switch back and forth without losing progress. 

Reason to do this is ability to read comments in AVPlayer mode but not in MPV mode. 

Maybe future feature?

### Device & OS Version

tvOS 16.4.1

### App Build

145

### App Settings

Latest invidious

**Comment by Insprill** [comment] 2023-05-10 06:19
Most likely a duplicate of #371.

**Comment by stonerl** [comment] 2024-05-23 11:59
This has been fixed.

**Closed by stonerl** 2024-05-23 11:59 UTC
Labels: bug
