### ISSUE TITLE
DOWNLOAD VIDEOS

### ISSUE THREAD

**Issue by revfast** [yattee/yattee#131] opened 2022-05-17 17:16 UTC
The app really surprised me, I think it’s really good so far, I would really think that adding a Download video option would make it killer.

**Comment by arekf** [comment] 2022-05-17 21:06
Glad you enjoy the app.

This is duplicate of #17. It is planned for the future, but hard to give ETA now.

**Closed by arekf** 2022-05-17 21:06 UTC
