### ISSUE TITLE
Piped Videos Not Playing with MPV

### ISSUE THREAD

**Issue by privacytime101** [yattee/yattee#400] opened 2023-02-11 20:26 UTC
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

Videos streamed from Piped will not play on Yattee when MPV is selected. It will display "Opening 1080p stream 0%", but nothing happens afterwards. Another user reported this to me and I was able to replicate it on every instance I tried. I was also able to confirm that the requests are going through to the server, so it's not necessarily a connection issue.

### Expected Behavior

MPV loads the video and the user's able to watch.

### Device & OS Version

iPhone, iOS 16.3

### App Build

112

### App Settings

From the default quality profile, I modified the "Wi-Fi" section under "Battery" to "MPV - 1080p" from "AVPlayer - 720p".

**Comment by derspyy** [comment] 2023-02-11 20:57
[yattee-124-mpv-log.txt](https://github.com/yattee/yattee/files/10714703/yattee-124-mpv-log.txt)
Dropping my mpv log for reference, since I'm having the same issue.

**Comment by arekf** [comment] 2023-02-25 14:08
This issue has been reported a few times and seems to be happening only on some instances but it's hard to say what's causing it. I don't have such issues with my private Piped instance. It may be some configuration difference that we've been unable to understand so if anyone has any clue, I'd like to hear it.

**Comment by FireMasterK** [comment] 2023-02-26 04:24
I'm pretty sure it's because of https://github.com/TeamPiped/piped-proxy/issues/8, will prioritize a fix for it.

Your instance might still be using the old Golang proxy. (The new one linked above is the Rust based replacement)

**Comment by arekf** [comment] 2023-03-13 09:56
I can see the fix has been merged to piped-proxy. Can anyone here confirm if after updating the instance this issue no longer exists in Yattee?

**Comment by derspyy** [comment] 2023-03-21 11:02
Doesn't seem to be fixed

**Comment by MatthiasGrandl** [comment] 2023-07-01 08:31
Also facing this issue (with the latest rust based proxy). Anyone who has been able to fix it?

**Comment by MatthiasGrandl** [comment] 2023-07-01 17:55
Just deployed Invidious on the same server and everything is working flawlessly. So definitely not a Yattee problem.

**Comment by julee** [comment] 2023-08-03 07:49
It appears to be a compatibility issue with the chunked encoding of ffmpeg, which mpv depends on. I was able to replicate this issue using the ffmpeg command line in version 4.2, and command line testing has confirmed that this issue was rectified by at least version 5.1. Who can guide me in compiling mpv for this project? I would like to verify.

The documentation for this project, as well as for mpv, does not specify how to compile the iOS version of libmpv.

**Comment by FireMasterK** [comment] 2023-08-03 23:17
It looks like you have pre-built binaries for mpv at https://github.com/yattee/yattee/tree/main/Vendor/mpv/macOS/lib

**Comment by arekf** [comment] 2023-09-23 21:10
Latest build 160 is using updated libraries, including ffmpeg 6.0

Can somebody confirm if this fixes the issue?

**Comment by derspyy** [comment] 2023-09-23 21:37
it's working well on invidious, at least.

**Comment by julee** [comment] 2023-09-26 15:04
Yes, it works now. 
The 1.5-162 version that I built and installed from the source code no longer has the issue of MPV failing to load and play, compared to the old version on the app store.

But in this version of the app, adding a new profile in the quality options of the settings will cause a crash:
```
2023-09-26T22:46:09+0800 info stream.yattee.cache.feed : [Yattee] caching feed feed-801028DE-43FA-40BD-9ED2-D706F8000DEA -- 2023-09-26T14:46:09Z
Yattee/QualityProfileForm.swift:230: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

**Comment by julee** [comment] 2023-09-27 01:38
> Latest build 160 is using updated libraries, including ffmpeg 6.0
> 
> Can somebody confirm if this fixes the issue?

May I ask if you can provide the compilation methods of mpv and ffmepg used in yattee? I am multimedia development engineer. I found that the mpv hardware decoding vp9 in yattee on my iPhone will fail. I want to debug and investigate the reason. I have experience in developing players based on technologies such as ffmpeg, videotoolbox, and mediacodec.

**Comment by MatthiasGrandl** [comment] 2023-09-27 07:55
I can confirm the latest builds work as expected with Piped. Allowed me to finally switch back to Piped! Thanks!

**Closed** 2024-05-18 09:42 UTC
Labels: bug
