### ISSUE TITLE
Piped's api for getting channel's Livestreams and shorts video list

### ISSUE THREAD

**Issue by upstroke-version** [yattee/yattee#352] opened 2022-11-23 13:59 UTC
This is a followup issue of https://github.com/yattee/yattee/issues/336

The api for livestream video tab is this:
https://pipedapi.kavin.rocks/channels/tabs?data={"originalUrl":"https://www.youtube.com/CHANNELID/streams","url":"https://www.youtube.com/CHANNELID/streams","id":"CHANNELID","contentFilters":["livestreams"],"sortFilter":"","baseUrl":"https://www.youtube.com"}

-Replace the "CHANNELID" with wanted channel ID.
-url might need to be encoded, I decoded just for readability imporvement.
-replace ["livestreams"] with ["shorts"] for short videos list.

I think support for viewing channel's livestream archive and shorts video is quite important.
I'm not sure the lack of api(or lack of piped api documentation) was bottleneck for supporting this feature, maybe you already knew this api, but I wish this was helpful for development and I wish users would be able to use this feature on this wonderful app.

**Comment by arekf** [comment] 2022-12-04 00:28
This will be fixed with next release. Thanks for the analysis, I was holding up with this as Invidious has no fix for that yet, but I'll fix at least on Piped for now.

Closing this as duplicate of #336, please don't open multiple issues for the same problem.

**Closed by arekf** 2022-12-04 00:28 UTC
